theme: jekyll-theme-architect

title: SAVE THE CORALS
description: [Coral reefs worldwide are facing severe threats that jeopardize their survival and have already led to degradation and destruction in many places. New management actions are desperately needed to ensure reefs continue to exist and recover their structure and function where that has been compromised. Fortunately, scientists, conservationists, and environmental managers across the globe are developing and implementing new strategies to protect and conserve these ecosystems against a suite of local and global threats.]
